name: ${project.name}
version: ${project.version}
main: com.ovidius.xorealis.duels.XorealisDuels
api-version: '1.21'
author: SnappyWave
description: A powerful plugin to Xorealis server.
softdepend: [Multiverse-Core]
commands:
  leavequeue:
    description: Позволяет игроку покинуть очередь на дуэль.
    usage: "/<command>"
    aliases: [lq,ql]
  duels:
    description: Главная команда плагина XorealisDuels.
    usage: "/<command> [reload]"
    aliases: [duel]
  party:
    description: Управление вашей пати для командных дуэлей
    usage: "/<command> [create|invite|accept|leave|kick|list]"
    aliases: [p]
permissions:
  xorealis.duels.reload:
    description: Дает доступ к комманде /duels reload
    default: op
  xorealis.duels.forcestop:
    description: Дает доступ к комманде /duels forcestop
    default: op
  xorealis.duels.forcestart:
    description: Дает доступ к комманде /duels forcestart
    default: op