name: ${project.name}
version: ${project.version}
main: com.ovidius.xorealis.duels.XorealisDuels
api-version: '1.21'
author: SnappyWave
description: A powerful plugin to Xorealis server.
softdepend: [Multiverse-Core]